language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:codegear/release -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq premake4 build-essential gcc-multilib lib32stdc++6 libc6-dev-i386
  - sudo apt-get install -qq g++-4.8
  - sudo ln -s /usr/lib32/libstdc++.so.6 /usr/lib32/libstdc++.so
before_script:
  - cd ./build/
  - premake4 gmake
script:
  - make config=debug32 && ../bin/Linux/debug32/waterspout
  - make config=release32 && ../bin/Linux/release32/waterspout
  - make config=debug64 && ../bin/Linux/debug64/waterspout
  - make config=release64 && ../bin/Linux/release64/waterspout
