language: cpp

sudo: false

git:
  depth: 1
  submodules: true

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-4.8-multilib
          - lib32stdc++6
          - libc6-dev-i386
      env: COMPILER=g++-4.8

    - os: linux
      compiler: clang
      env: COMPILER=clang++

before_script:
  - cd ./build/
  - chmod 755 premake4.lnx
  - ./premake4.lnx gmake

script:
  - if [ "$COMPILER" = "g++-4.8" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$COMPILER" = "clang++" ]; then export CXX="clang++" CC="clang"; fi
  - make config=debug32 && ../bin/Linux/debug32/waterspout
  - make config=release32 && ../bin/Linux/release32/waterspout
  - make config=debug64 && ../bin/Linux/debug64/waterspout
  - make config=release64 && ../bin/Linux/release64/waterspout
