language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang-3.4
before_install:
  - sudo add-apt-repository ppa:codegear/release -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq premake4 lib32stdc++6 libc6-dev-i386
  - sudo ln -s /usr/lib32/libstdc++.so.6 /usr/lib32/libstdc++.so
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4" CC="clang-3.4"; fi
before_script:
  - cd ./build/
  - premake4 gmake
  - $CXX --version
script:
  - make config=debug32 && ../bin/Linux/debug32/waterspout
  - make config=release32 && ../bin/Linux/release32/waterspout
  - make config=debug64 && ../bin/Linux/debug64/waterspout
  - make config=release64 && ../bin/Linux/release64/waterspout
