language: cpp

sudo: required

git:
  depth: 1
  submodules: true

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=gcc++-4.8

    - os: linux
      compiler: clang
      env: COMPILER=clang++

    - os: osx
      compiler: clang
      env: COMPILER=clang++

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq g++-4.8-multilib lib32stdc++6 libc6-dev-i386; export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - cd ./build/
  - ls
  - chmod 755 premake4.lnx
  - ./premake4.lnx gmake

script:
  - if [ "$COMPILER" = "g++-4.8" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$COMPILER" = "clang++" ]; then export CXX="clang++" CC="clang"; fi
  - make config=debug32 && ../bin/Linux/debug32/waterspout
  - make config=release32 && ../bin/Linux/release32/waterspout
  - make config=debug64 && ../bin/Linux/debug64/waterspout
  - make config=release64 && ../bin/Linux/release64/waterspout
