language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-add-repository -y ppa:comp-phys/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq premake4 build-essential gcc-multilib lib32stdc++6 libc6-dev-i386 g++-4.8
  - sudo ln -s /usr/lib32/libstdc++.so.6 /usr/lib32/libstdc++.so
  - [ "$CXX" = "g++" ] && export CXX="g++-4.8" CC="gcc-4.8
before_script:
  - cd ./build/
  - premake4 gmake
script:
  - make config=debug32 && ../bin/Linux/debug32/waterspout
  - make config=release32 && ../bin/Linux/release32/waterspout
  - make config=debug64 && ../bin/Linux/debug64/waterspout
  - make config=release64 && ../bin/Linux/release64/waterspout
