version: x.{build}

configuration:
- debug
- release

environment:
  matrix:
  - VS_VERSION: 10
    VS_PLATFORM: win32
  - VS_VERSION: 10
    VS_PLATFORM: x64

before_build:
- cd build
- premake4.exe vs2010 

build:
  project: waterspout.sln
  parallel: true
  verbosity: minimal
