version: x.{build}

configuration:
- debug
- release

environment:
  matrix:
  - VS_VERSION: 12
    VS_PLATFORM: win32
  - VS_VERSION: 12
    VS_PLATFORM: x64

before_build:
- cd build
- premake4.exe vs2010
- dir
- cd ..

build:
  project: build\waterspout.vcxproj
  parallel: true
  verbosity: minimal

test_script:
- if exist bin\Windows\debug32\waterspout.exe bin\Windows\debug32\waterspout.exe
- if exist bin\Windows\release32\waterspout.exe bin\Windows\release32\waterspout.exe
- if exist bin\Windows\debug64\waterspout.exe bin\Windows\debug64\waterspout.exe
- if exist bin\Windows\release64\waterspout.exe bin\Windows\release64\waterspout.exe
